"""initial

Revision ID: 26be3ee10386
Revises: d65c2e235c8b
Create Date: 2025-11-29 18:12:57.590481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26be3ee10386'
down_revision = 'd65c2e235c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('logs_resource_id_fkey'), type_='foreignkey')
        batch_op.drop_column('resource_id')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('logs_resource_id_fkey'), 'resources', ['resource_id'], ['id'])

    # ### end Alembic commands ###
